#!/bin/bash

#arguments
x3dfile=$1

imagepath=$2

# directory where this script (screenshot) is located
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# try to run rayhunter with system-programmes
$DIR/rayhunter/rayhunter -p 1 1 3 -d -0.4 -0.2 -1 --scene-bg-color 1 1 1 classic 10 300 300 $1 $2

if [ "$?" -ne "0" ]
then
	# above command does not work so try to run the programme via juju
	export PATH=$PATH:$DIR/juju/bin
	export HOME=/home/henm1415g2
	juju <<< "$DIR/rayhunter/rayhunter -p 1 1 3 -d -0.4 -0.2 -1 --scene-bg-color 1 1 1 classic 10 300 300 $x3dfile $imagepath"
fi
