<?php 
/**
 * Copyright 2015 Adam Brunnmeier, Dominik Studer, Alexandra Wörner, Frederik Zwilling, Ali Demiralp, Dev Sharma, Luca Liehner, Marco Dung, Georgios Toubekis
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @file register_as_tutor.php
 * Sends emails to admins to request being "confirmed" in database. 
 */
  
  ob_start();
  
  require '../php/db_connect.php';
  require '../config/config.php';
  
  ////// Get email from calling user    die(true);
  session_start();
  if(! isset($_SESSION['access_token'])) {
  	die('User needs to be logged in to register as tutor.');
  }
  
  // from fake login
  $email = $_SESSION['email'];
  // fake_end

  // TODO: get email from las2peer-service
  // see 'checkUserKnown.php' for getting user credentials from $_SESSION['access_token']

	$bAtLeastOne = false;
   // Send a mail to admins to inform that someone wants to register
   // The admins are defined in config/config.php
   foreach ($admins as $admin) {
     $mail_to = $admin["0"];
     $admin_name = $admin["1"] . " " . $admin["2"];
     $confirmation_link = $baseUrl . "/src/views/confirm_registration.php?mail=" . $email;
     $subject = "Anatomy 2.0 Lecturer";
     $message = "Hello " . $admin_name . ",\n\n" .
       $email . "\n wants to be granted lecturer rights at Anatomy2.0.\n" .
       "If the email address belongs to a lecturer, please confirm his or her account by clicking the following link: " . $confirmation_link . "\n" . 
       "After a short delay, the account should then be confirmed automatically." . "\n\n" .
       "This mail was automatically generated by the Anatomy 2.0 system. Please do not respond to this mail.";
     $bAtLeastOne = mail($mail_to, $subject, $message) or $bAtLeastOne;
   }
   
   ob_end_clean();
      
   echo json_encode(['result'=>$bAtLeastOne]);
