<?php 
  
  include '../php/db_connect.php';
  require '../config/config.php';
  
  $email = $_POST['register_email'];
  $pw = md5($_POST['register_pw']);
  
  // Use only when debugging
  //$db->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING );
  
  // Test whether there is already an account for the given email address
  $sql = "SELECT * FROM users WHERE email='" . $email . "'";
  $sth = $db->prepare($sql);
  $sth->execute();
  // As there can be only one row in the result, get the first row
  $user = $sth->fetch();
  // If user is not empty, the account can be created
  if($user) {
    $result = array('result'=>'error', 'sql'=>$sql, 'error_msg'=>'There already exists an account for the email address ' . $email );
  }
  else { // Create an account
    $sql = "INSERT INTO users (email, pass) VALUES ('$email','$pw')";
    
    // This will escape symbols in the SQL statement (also supposed to prevent 
    // SQL injection attacks). Returns a PDOStatement
    $sth = $db->prepare($sql);
    // Executes the select statement on DB
    $success = $sth->execute();
    
    $a1 = array("t1", "t2", "t3");
    $a2 = array("b1", "b2", "b3");
    $a = array($a1, $a2);
    
    if ($success) {
      // Send a mail to admins to inform that someone wants to register
      // The admins are defined in config/config.php
      foreach ($admins as $admin) {
        $mail_to = $admin["0"];
        $admin_name = $admin["1"] . " " . $admin["2"];
        $confirmation_link = $baseUrl . "/src/views/confirm_registration.php?mail=" . $email;
        $subject = "Anatomy 2.0 Registration";
        $message = "Hello " . $admin_name . ",\n\n" .
          "someone registered to Anatomy2.0 with the following email address: " . $email . "\n" .
          "If the email address belongs to a lecturer, please confirm his or her account by clicking the following link: " . $confirmation_link . "\n" . 
          "After a short delay, the account should then be confirmed automatically." . "\n\n" .
          "This mail was automatically generated by the Anatomy 2.0 system. Please do not respond to this mail.";
        mail($mail_to, $subject, $message);
      }
      
      // Create result to transmit to client. SQL is sent only for debugging
      $result = array('result'=>'ok', 'sql'=>$sql, 'admins'=>$admins, 'test'=>$admin_name);		
    }
    else {
      $result = array('result'=>'error', 'sql'=>$sql);		
    }
  }

  // JSON encode the return value to be transmitted to client again
  echo json_encode($result);
?>